### ISSUE TITLE
Formatter not formatting 

### ISSUE THREAD

**Issue by hariso** [timonwong/SublimeAStyleFormatter#39]
Hi,

I'm using SublimeAStyleFormatter v2.1.0, with Apex and Java files. Whether I use "Format current file" or "Format selection", it doesn't work, although it says in the status bar "AStyle (v2.04) Formatted." 

Any hints on how to get this working?

Best wishes,

Haris

**Comment by garfieldnate** [comment]
I had the same problem. I turned on debugging in the package settings, and it turned out that the astyle call was failing because of some unsupported options (timonwong/pyastyle/issues/2).
Turn on debugging and see if you get anything.

As for a fix, I think it would be helpful if a message were given at the bottom of the window saying "astyle failed: unknown options" or something. Mine doesn't display any message at all when the call to astyle fails.

**Comment by timonwong** [comment]
@garfieldnate 
Because SublimeAStyleFormatter send contents of source code as buffer, and called pyastyle directly, so there is no "file" options, listed here: http://astyle.sourceforge.net/astyle.html#_Other_Options

I'll update the pyastyle package, and strip those options when formatting, thanks for reporting

**Comment by pranavsingh0410** [comment]
I am using SublimeAStyleFormatter on mac m1 but it does'nt work at all.
Please help on how to get this woking 
Thanks
Pranav
